### ISSUE TITLE
sms page is not revealing code entry field

### ISSUE THREAD

**Issue by jenbrannstrom** [jenbrannstrom/gaza#3]
the page at http://int.thewaytohappinessstl.org/sms/
accepts the name & phonenumber, and an sms is received on my mobile.
However the field to enter the code doesn't appear - the page just hangs

http://prntscr.com/6prl3s

**Comment by shailesh91** [comment]
This is a Cross-Origin Resource Sharing.

**Comment by jenbrannstrom** [comment]
ok, how do we make it work?

**Comment by shailesh91** [comment]
I modified some code on the other server. Can you try again.

On Sunday, April 5, 2015, Jen Brannstrom notifications@github.com wrote:

> ok, how do we make it work?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jenbrannstrom/gaza/issues/3#issuecomment-89827221.

## 

## 

Regards
Shailesh Goel

Email   : shailesh912@gmail.com
Skype  : shailesh916
Phone  : +91-9780493275

**Comment by jenbrannstrom** [comment]
yes, works, but redirects to http://int.thewaytohappinessstl.org/sms/thankyou.php

which is 404 on gh-pages (since it is PHP)

**Comment by shailesh91** [comment]
I will correct this. The Arabic problem I will have to check out. Not sure
the cause. Maybe the CORS thing is the reason.

On Monday, April 6, 2015, Jen Brannstrom notifications@github.com wrote:

> yes, works, but redirects to
> http://int.thewaytohappinessstl.org/sms/thankyou.php
> 
> which is 404 on gh-pages (since it is PHP)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jenbrannstrom/gaza/issues/3#issuecomment-89862107.

## 

## 

Regards
Shailesh Goel

Email   : shailesh912@gmail.com
Skype  : shailesh916
Phone  : +91-9780493275

**Comment by jenbrannstrom** [comment]
fixed
page goes to: http://int.thewaytohappinessstl.org/sms/thankyou.html
