### ISSUE TITLE
Arabic name text corrupted

### ISSUE THREAD

**Issue by jenbrannstrom** [jenbrannstrom/gaza#4]
http://prntscr.com/6q1eov
Arabic name field is being corrupted in DB

**Comment by shailesh91** [comment]
Jen, I have added something to the JS to counter this. Can you please check
this if it works.

On Mon, Apr 6, 2015 at 3:31 AM, Jen Brannstrom notifications@github.com
wrote:

> Assigned #4 https://github.com/jenbrannstrom/gaza/issues/4 to
> @shailesh91 https://github.com/shailesh91.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jenbrannstrom/gaza/issues/4#event-273747494.

## 

## 

Regards
Shailesh Goel

Email   : shailesh912@gmail.com
Skype  : shailesh916
Phone  : +91-9780493275

**Comment by jenbrannstrom** [comment]
not really fixed:
http://prntscr.com/6q59zx
Is this not simply a UTF-8 problem?

**Comment by shailesh91** [comment]
Can you please check this again. I think it should be fixed now!

**Comment by jenbrannstrom** [comment]
http://prntscr.com/6q7t3j

**Comment by shailesh91** [comment]
Issue fixed!

**Comment by jenbrannstrom** [comment]
http://prntscr.com/6s6748 - yes, the arabic text is fine now!
the sms is sent, and arrives on my phone
But, the page doesn't change so I can enter the verif code: http://prntscr.com/6s670p

**Comment by jenbrannstrom** [comment]
Fixed!
