### ISSUE TITLE
copy page w Mailchimp webform

### ISSUE THREAD

**Issue by jenbrannstrom** [jenbrannstrom/gaza#7]
Hi Shailesh,
Please can you replicate this page,
http://int.thewaytohappinessstl.org/
 but using a Mailchimp form, from the Arabic Mailchimp account
(you already have access via your gmail)
Two fields are needed: Name & email.

Do it in English, and I will get it translated. Although it does have to all be RTL of the entire page & form

**Comment by shailesh91** [comment]
@jenbrannstrom : I will be able only able to do this over the weekend I think. I am out of station till 4th June.

**Comment by jenbrannstrom** [comment]
sure no problem

**Comment by shailesh91** [comment]
Done!
