### ISSUE TITLE
page-load measurement

### ISSUE THREAD

**Issue by jenbrannstrom** [jenbrannstrom/gaza#8]
as these pages are running in the Middle East, and they are hosted on Github, I wanted to make sure they are loading ok.

Can you test them using this new service:

https://portal.cedexis.com

username is jen@taptap.mobi
pass: E^^aT0b*2XI1

**Comment by shailesh91** [comment]
Hey @jenbrannstrom: Can you please tell me do I have to add any piece of code to the page? And what is the final outcome expected?

**Comment by jenbrannstrom** [comment]
yes, you can get a js code when you log in.
The end result is that we can see how the page functions in each person's browser. If theer are any delivery problems etc.

**Comment by shailesh91** [comment]
I have added the js code already.
